### ISSUE TITLE
Warning: foreach() argument must be of type array|object, null given in admin_bar_views_grouping_admin_bar_output_alter

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/admin_bar_views_grouping#2]
**Steps to reproduce**

1. I think this is PHP 8.1 behaviour so enable as PHP 8.1
2. Enable the module
3. Enable display of all errors and warnings
4. Have at least one role that can view admin bar but not administer views
5. Login as that role
6. Go to create content (for some reason doesn't trigger on the dashboard)

**Actual result**
Warning: foreach() argument must be of type array|object, null given in admin_bar_views_grouping_admin_bar_output_alter() (line 29 of /app/docroot/modules/contrib/admin_bar_views_grouping/admin_bar_views_grouping.module).

**Expected result**
No error or warning

**Comment by yorkshire-pudding** [comment]
@bugfolder - not sure whether just requesting a PR review pings you or not, so also pinging you here.

**Comment by bugfolder** [comment]
Duly pinged! Reviewed PR. It does the job, so RTBC. Thanks, @yorkshire-pudding!
